/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceStatus {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatus>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceStatus {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceStatus {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceStatus {
            status: None,
        }
    }
}


