/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodRawArtifact : RawArtifact allows raw string content to be placed as an artifact in a container



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodRawArtifact {
    /// Data is the string contents of the artifact
    #[serde(rename = "data")]
    pub data: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodRawArtifact {
    /// RawArtifact allows raw string content to be placed as an artifact in a container
    pub fn new(data: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodRawArtifact {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodRawArtifact {
            data,
        }
    }
}


