/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodWatchPathConfig {
    #[serde(rename = "directory", skip_serializing_if = "Option::is_none")]
    pub directory: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "pathRegexp", skip_serializing_if = "Option::is_none")]
    pub path_regexp: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodWatchPathConfig {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodWatchPathConfig {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodWatchPathConfig {
            directory: None,
            path: None,
            path_regexp: None,
        }
    }
}


