/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarEventSource {
    #[serde(rename = "authTokenSecret", skip_serializing_if = "Option::is_none")]
    pub auth_token_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "connectionBackoff", skip_serializing_if = "Option::is_none")]
    pub connection_backoff: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBackoff>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceFilter>>,
    #[serde(rename = "jsonBody", skip_serializing_if = "Option::is_none")]
    pub json_body: Option<bool>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "tls", skip_serializing_if = "Option::is_none")]
    pub tls: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig>>,
    #[serde(rename = "tlsAllowInsecureConnection", skip_serializing_if = "Option::is_none")]
    pub tls_allow_insecure_connection: Option<bool>,
    #[serde(rename = "tlsTrustCertsSecret", skip_serializing_if = "Option::is_none")]
    pub tls_trust_certs_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "tlsValidateHostname", skip_serializing_if = "Option::is_none")]
    pub tls_validate_hostname: Option<bool>,
    #[serde(rename = "topics", skip_serializing_if = "Option::is_none")]
    pub topics: Option<Vec<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarEventSource {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarEventSource {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarEventSource {
            auth_token_secret: None,
            connection_backoff: None,
            filter: None,
            json_body: None,
            metadata: None,
            tls: None,
            tls_allow_insecure_connection: None,
            tls_trust_certs_secret: None,
            tls_validate_hostname: None,
            topics: None,
            r#type: None,
            url: None,
        }
    }
}


