/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBitbucketAuth {
    #[serde(rename = "basic", skip_serializing_if = "Option::is_none")]
    pub basic: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBitbucketBasicAuth>>,
    #[serde(rename = "oauthToken", skip_serializing_if = "Option::is_none")]
    pub oauth_token: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBitbucketAuth {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBitbucketAuth {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBitbucketAuth {
            basic: None,
            oauth_token: None,
        }
    }
}


