/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodKafkaConsumerGroup {
    #[serde(rename = "groupName", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "oldest", skip_serializing_if = "Option::is_none")]
    pub oldest: Option<bool>,
    #[serde(rename = "rebalanceStrategy", skip_serializing_if = "Option::is_none")]
    pub rebalance_strategy: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodKafkaConsumerGroup {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodKafkaConsumerGroup {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodKafkaConsumerGroup {
            group_name: None,
            oldest: None,
            rebalance_strategy: None,
        }
    }
}


