/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodOpenWhiskTrigger : OpenWhiskTrigger refers to the specification of the OpenWhisk trigger.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodOpenWhiskTrigger {
    /// Name of the action/function.
    #[serde(rename = "actionName", skip_serializing_if = "Option::is_none")]
    pub action_name: Option<String>,
    #[serde(rename = "authToken", skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    /// Host URL of the OpenWhisk.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Namespace for the action. Defaults to \"_\". +optional.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerParameter>>,
    /// Payload is the list of key-value extracted from an event payload to construct the request payload.
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Vec<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerParameter>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodOpenWhiskTrigger {
    /// OpenWhiskTrigger refers to the specification of the OpenWhisk trigger.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodOpenWhiskTrigger {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodOpenWhiskTrigger {
            action_name: None,
            auth_token: None,
            host: None,
            namespace: None,
            parameters: None,
            payload: None,
            version: None,
        }
    }
}


