/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodWeightedPodAffinityTerm : The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodWeightedPodAffinityTerm {
    #[serde(rename = "podAffinityTerm")]
    pub pod_affinity_term: Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPodAffinityTerm>,
    /// weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
    #[serde(rename = "weight")]
    pub weight: i32,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodWeightedPodAffinityTerm {
    /// The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
    pub fn new(pod_affinity_term: crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPodAffinityTerm, weight: i32) -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodWeightedPodAffinityTerm {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodWeightedPodAffinityTerm {
            pod_affinity_term: Box::new(pod_affinity_term),
            weight,
        }
    }
}


