/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactGcSpec : ArtifactGCSpec specifies the Artifacts that need to be deleted



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactGcSpec {
    /// ArtifactsByNode maps Node name to information pertaining to Artifacts on that Node
    #[serde(rename = "artifactsByNode", skip_serializing_if = "Option::is_none")]
    pub artifacts_by_node: Option<::std::collections::HashMap<String, crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactNodeSpec>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactGcSpec {
    /// ArtifactGCSpec specifies the Artifacts that need to be deleted
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactGcSpec {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactGcSpec {
            artifacts_by_node: None,
        }
    }
}


