/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatusPolicy {
    #[serde(rename = "allow", skip_serializing_if = "Option::is_none")]
    pub allow: Option<Vec<i32>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatusPolicy {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatusPolicy {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatusPolicy {
            allow: None,
        }
    }
}


