/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodInt64OrString {
    #[serde(rename = "int64Val", skip_serializing_if = "Option::is_none")]
    pub int64_val: Option<String>,
    #[serde(rename = "strVal", skip_serializing_if = "Option::is_none")]
    pub str_val: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodInt64OrString {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodInt64OrString {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodInt64OrString {
            int64_val: None,
            str_val: None,
            r#type: None,
        }
    }
}


