/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection : Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection {
    /// Items is a list of DownwardAPIVolume file
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiVolumeFile>>,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection {
    /// Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
    pub fn new() -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection {
            items: None,
        }
    }
}


