/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodClientCertAuth : ClientCertAuth holds necessary information for client authentication via certificates



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodClientCertAuth {
    #[serde(rename = "clientCertSecret", skip_serializing_if = "Option::is_none")]
    pub client_cert_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "clientKeySecret", skip_serializing_if = "Option::is_none")]
    pub client_key_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodClientCertAuth {
    /// ClientCertAuth holds necessary information for client authentication via certificates
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodClientCertAuth {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodClientCertAuth {
            client_cert_secret: None,
            client_key_secret: None,
        }
    }
}


