/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodVolumeClaimGc : VolumeClaimGC describes how to delete volumes from completed Workflows



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodVolumeClaimGc {
    /// Strategy is the strategy to use. One of \"OnWorkflowCompletion\", \"OnWorkflowSuccess\". Defaults to \"OnWorkflowSuccess\"
    #[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
    pub strategy: Option<String>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodVolumeClaimGc {
    /// VolumeClaimGC describes how to delete volumes from completed Workflows
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodVolumeClaimGc {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodVolumeClaimGc {
            strategy: None,
        }
    }
}


