/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimTemplate : PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimTemplate {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::IoPeriodK8sPeriodApimachineryPeriodPkgPeriodApisPeriodMetaPeriodV1PeriodObjectMeta>>,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimSpec>,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimTemplate {
    /// PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
    pub fn new(spec: crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimSpec) -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimTemplate {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPersistentVolumeClaimTemplate {
            metadata: None,
            spec: Box::new(spec),
        }
    }
}


