/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventPersistence {
    #[serde(rename = "catchup", skip_serializing_if = "Option::is_none")]
    pub catchup: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCatchupConfiguration>>,
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConfigMapPersistence>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventPersistence {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventPersistence {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventPersistence {
            catchup: None,
            config_map: None,
        }
    }
}


