/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodK8sPeriodApiPeriodPolicyPeriodV1PeriodPodDisruptionBudgetSpec : PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodPolicyPeriodV1PeriodPodDisruptionBudgetSpec {
    #[serde(rename = "maxUnavailable", skip_serializing_if = "Option::is_none")]
    pub max_unavailable: Option<String>,
    #[serde(rename = "minAvailable", skip_serializing_if = "Option::is_none")]
    pub min_available: Option<String>,
    #[serde(rename = "selector", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Box<crate::models::IoPeriodK8sPeriodApimachineryPeriodPkgPeriodApisPeriodMetaPeriodV1PeriodLabelSelector>>,
}

impl IoPeriodK8sPeriodApiPeriodPolicyPeriodV1PeriodPodDisruptionBudgetSpec {
    /// PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.
    pub fn new() -> IoPeriodK8sPeriodApiPeriodPolicyPeriodV1PeriodPodDisruptionBudgetSpec {
        IoPeriodK8sPeriodApiPeriodPolicyPeriodV1PeriodPodDisruptionBudgetSpec {
            max_unavailable: None,
            min_available: None,
            selector: None,
        }
    }
}


