/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronizationStatus : SynchronizationStatus stores the status of semaphore and mutex.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronizationStatus {
    #[serde(rename = "mutex", skip_serializing_if = "Option::is_none")]
    pub mutex: Option<Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMutexStatus>>,
    #[serde(rename = "semaphore", skip_serializing_if = "Option::is_none")]
    pub semaphore: Option<Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreStatus>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronizationStatus {
    /// SynchronizationStatus stores the status of semaphore and mutex.
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronizationStatus {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronizationStatus {
            mutex: None,
            semaphore: None,
        }
    }
}


