/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodK8SResourcePolicy {
    #[serde(rename = "backoff", skip_serializing_if = "Option::is_none")]
    pub backoff: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBackoff>>,
    #[serde(rename = "errorOnBackoffTimeout", skip_serializing_if = "Option::is_none")]
    pub error_on_backoff_timeout: Option<bool>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodK8SResourcePolicy {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodK8SResourcePolicy {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodK8SResourcePolicy {
            backoff: None,
            error_on_backoff_timeout: None,
            labels: None,
        }
    }
}


