/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLink : A link to another app.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLink {
    /// The name of the link, E.g. \"Workflow Logs\" or \"Pod Logs\"
    #[serde(rename = "name")]
    pub name: String,
    /// \"workflow\", \"pod\", \"pod-logs\", \"event-source-logs\", \"sensor-logs\", \"workflow-list\" or \"chat\"
    #[serde(rename = "scope")]
    pub scope: String,
    /// The URL. Can contain \"${metadata.namespace}\", \"${metadata.name}\", \"${status.startedAt}\", \"${status.finishedAt}\" or any other element in workflow yaml, e.g. \"${io.argoproj.workflow.v1alpha1.metadata.annotations.userDefinedKey}\"
    #[serde(rename = "url")]
    pub url: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLink {
    /// A link to another app.
    pub fn new(name: String, scope: String, url: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLink {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLink {
            name,
            scope,
            url,
        }
    }
}


