/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCatchupConfiguration {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "maxDuration", skip_serializing_if = "Option::is_none")]
    pub max_duration: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCatchupConfiguration {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCatchupConfiguration {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCatchupConfiguration {
            enabled: None,
            max_duration: None,
        }
    }
}


