/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodArtifactLocation {
    #[serde(rename = "configmap", skip_serializing_if = "Option::is_none")]
    pub configmap: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodConfigMapKeySelector>>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodFileArtifact>>,
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitArtifact>>,
    #[serde(rename = "inline", skip_serializing_if = "Option::is_none")]
    pub inline: Option<String>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodResource>>,
    #[serde(rename = "s3", skip_serializing_if = "Option::is_none")]
    pub s3: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodS3Artifact>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodUrlArtifact>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodArtifactLocation {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodArtifactLocation {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodArtifactLocation {
            configmap: None,
            file: None,
            git: None,
            inline: None,
            resource: None,
            s3: None,
            url: None,
        }
    }
}


