/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPubSubEventSource : PubSubEventSource refers to event-source for GCP PubSub related events.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPubSubEventSource {
    #[serde(rename = "credentialSecret", skip_serializing_if = "Option::is_none")]
    pub credential_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "deleteSubscriptionOnFinish", skip_serializing_if = "Option::is_none")]
    pub delete_subscription_on_finish: Option<bool>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceFilter>>,
    #[serde(rename = "jsonBody", skip_serializing_if = "Option::is_none")]
    pub json_body: Option<bool>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "projectID", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "subscriptionID", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "topicProjectID", skip_serializing_if = "Option::is_none")]
    pub topic_project_id: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPubSubEventSource {
    /// PubSubEventSource refers to event-source for GCP PubSub related events.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPubSubEventSource {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPubSubEventSource {
            credential_secret: None,
            delete_subscription_on_finish: None,
            filter: None,
            json_body: None,
            metadata: None,
            project_id: None,
            subscription_id: None,
            topic: None,
            topic_project_id: None,
        }
    }
}


