/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection : Projection that may be projected along with other supported volume types



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodConfigMapProjection>>,
    #[serde(rename = "downwardAPI", skip_serializing_if = "Option::is_none")]
    pub downward_api: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection>>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretProjection>>,
    #[serde(rename = "serviceAccountToken", skip_serializing_if = "Option::is_none")]
    pub service_account_token: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodServiceAccountTokenProjection>>,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
    /// Projection that may be projected along with other supported volume types
    pub fn new() -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
            config_map: None,
            downward_api: None,
            secret: None,
            service_account_token: None,
        }
    }
}


