/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodAffinity : Affinity is a group of affinity scheduling rules.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodAffinity {
    #[serde(rename = "nodeAffinity", skip_serializing_if = "Option::is_none")]
    pub node_affinity: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodNodeAffinity>>,
    #[serde(rename = "podAffinity", skip_serializing_if = "Option::is_none")]
    pub pod_affinity: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPodAffinity>>,
    #[serde(rename = "podAntiAffinity", skip_serializing_if = "Option::is_none")]
    pub pod_anti_affinity: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPodAntiAffinity>>,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodAffinity {
    /// Affinity is a group of affinity scheduling rules.
    pub fn new() -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodAffinity {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodAffinity {
            node_affinity: None,
            pod_affinity: None,
            pod_anti_affinity: None,
        }
    }
}


