/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTemplate {
    #[serde(rename = "affinity", skip_serializing_if = "Option::is_none")]
    pub affinity: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodAffinity>>,
    #[serde(rename = "container", skip_serializing_if = "Option::is_none")]
    pub container: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodContainer>>,
    #[serde(rename = "imagePullSecrets", skip_serializing_if = "Option::is_none")]
    pub image_pull_secrets: Option<Vec<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodLocalObjectReference>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodMetadata>>,
    #[serde(rename = "nodeSelector", skip_serializing_if = "Option::is_none")]
    pub node_selector: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "priorityClassName", skip_serializing_if = "Option::is_none")]
    pub priority_class_name: Option<String>,
    #[serde(rename = "securityContext", skip_serializing_if = "Option::is_none")]
    pub security_context: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPodSecurityContext>>,
    #[serde(rename = "serviceAccountName", skip_serializing_if = "Option::is_none")]
    pub service_account_name: Option<String>,
    #[serde(rename = "tolerations", skip_serializing_if = "Option::is_none")]
    pub tolerations: Option<Vec<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodToleration>>,
    #[serde(rename = "volumes", skip_serializing_if = "Option::is_none")]
    pub volumes: Option<Vec<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolume>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTemplate {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTemplate {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTemplate {
            affinity: None,
            container: None,
            image_pull_secrets: None,
            metadata: None,
            node_selector: None,
            priority: None,
            priority_class_name: None,
            security_context: None,
            service_account_name: None,
            tolerations: None,
            volumes: None,
        }
    }
}


