/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConditionsResetCriteria {
    #[serde(rename = "byTime", skip_serializing_if = "Option::is_none")]
    pub by_time: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConditionsResetByTime>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConditionsResetCriteria {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConditionsResetCriteria {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConditionsResetCriteria {
            by_time: None,
        }
    }
}


