/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGithubAppCreds {
    #[serde(rename = "appID", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    #[serde(rename = "installationID", skip_serializing_if = "Option::is_none")]
    pub installation_id: Option<String>,
    #[serde(rename = "privateKey", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGithubAppCreds {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGithubAppCreds {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGithubAppCreds {
            app_id: None,
            installation_id: None,
            private_key: None,
        }
    }
}


