/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowEventBindingSpec {
    #[serde(rename = "event")]
    pub event: Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodEvent>,
    #[serde(rename = "submit", skip_serializing_if = "Option::is_none")]
    pub submit: Option<Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSubmit>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowEventBindingSpec {
    pub fn new(event: crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodEvent) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowEventBindingSpec {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowEventBindingSpec {
            event: Box::new(event),
            submit: None,
        }
    }
}


