/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceFilter {
    #[serde(rename = "expression", skip_serializing_if = "Option::is_none")]
    pub expression: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceFilter {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceFilter {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodEventSourceFilter {
            expression: None,
        }
    }
}


