/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarTrigger : PulsarTrigger refers to the specification of the Pulsar trigger.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarTrigger {
    #[serde(rename = "authTokenSecret", skip_serializing_if = "Option::is_none")]
    pub auth_token_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "connectionBackoff", skip_serializing_if = "Option::is_none")]
    pub connection_backoff: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodBackoff>>,
    /// Parameters is the list of parameters that is applied to resolved Kafka trigger object.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerParameter>>,
    /// Payload is the list of key-value extracted from an event payload to construct the request payload.
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Vec<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerParameter>>,
    #[serde(rename = "tls", skip_serializing_if = "Option::is_none")]
    pub tls: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig>>,
    #[serde(rename = "tlsAllowInsecureConnection", skip_serializing_if = "Option::is_none")]
    pub tls_allow_insecure_connection: Option<bool>,
    #[serde(rename = "tlsTrustCertsSecret", skip_serializing_if = "Option::is_none")]
    pub tls_trust_certs_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "tlsValidateHostname", skip_serializing_if = "Option::is_none")]
    pub tls_validate_hostname: Option<bool>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarTrigger {
    /// PulsarTrigger refers to the specification of the Pulsar trigger.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarTrigger {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarTrigger {
            auth_token_secret: None,
            connection_backoff: None,
            parameters: None,
            payload: None,
            tls: None,
            tls_allow_insecure_connection: None,
            tls_trust_certs_secret: None,
            tls_validate_hostname: None,
            topic: None,
            url: None,
        }
    }
}


