/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCounter : Counter is a Counter prometheus metric



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCounter {
    /// Value is the value of the metric
    #[serde(rename = "value")]
    pub value: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCounter {
    /// Counter is a Counter prometheus metric
    pub fn new(value: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCounter {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCounter {
            value,
        }
    }
}


