/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerTemplate : TriggerTemplate is the template that describes trigger specification.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerTemplate {
    #[serde(rename = "argoWorkflow", skip_serializing_if = "Option::is_none")]
    pub argo_workflow: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodArgoWorkflowTrigger>>,
    #[serde(rename = "awsLambda", skip_serializing_if = "Option::is_none")]
    pub aws_lambda: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAwsLambdaTrigger>>,
    #[serde(rename = "azureEventHubs", skip_serializing_if = "Option::is_none")]
    pub azure_event_hubs: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAzureEventHubsTrigger>>,
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<String>,
    #[serde(rename = "conditionsReset", skip_serializing_if = "Option::is_none")]
    pub conditions_reset: Option<Vec<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodConditionsResetCriteria>>,
    #[serde(rename = "custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCustomTrigger>>,
    #[serde(rename = "http", skip_serializing_if = "Option::is_none")]
    pub http: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodHttpTrigger>>,
    #[serde(rename = "k8s", skip_serializing_if = "Option::is_none")]
    pub k8s: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStandardK8STrigger>>,
    #[serde(rename = "kafka", skip_serializing_if = "Option::is_none")]
    pub kafka: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodKafkaTrigger>>,
    #[serde(rename = "log", skip_serializing_if = "Option::is_none")]
    pub log: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodLogTrigger>>,
    /// Name is a unique name of the action to take.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nats", skip_serializing_if = "Option::is_none")]
    pub nats: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodNatsTrigger>>,
    #[serde(rename = "openWhisk", skip_serializing_if = "Option::is_none")]
    pub open_whisk: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodOpenWhiskTrigger>>,
    #[serde(rename = "pulsar", skip_serializing_if = "Option::is_none")]
    pub pulsar: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodPulsarTrigger>>,
    #[serde(rename = "slack", skip_serializing_if = "Option::is_none")]
    pub slack: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSlackTrigger>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerTemplate {
    /// TriggerTemplate is the template that describes trigger specification.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerTemplate {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTriggerTemplate {
            argo_workflow: None,
            aws_lambda: None,
            azure_event_hubs: None,
            conditions: None,
            conditions_reset: None,
            custom: None,
            http: None,
            k8s: None,
            kafka: None,
            log: None,
            name: None,
            nats: None,
            open_whisk: None,
            pulsar: None,
            slack: None,
        }
    }
}


