/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronization : Synchronization holds synchronization lock configuration



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronization {
    #[serde(rename = "mutex", skip_serializing_if = "Option::is_none")]
    pub mutex: Option<Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMutex>>,
    #[serde(rename = "semaphore", skip_serializing_if = "Option::is_none")]
    pub semaphore: Option<Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreRef>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronization {
    /// Synchronization holds synchronization lock configuration
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronization {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSynchronization {
            mutex: None,
            semaphore: None,
        }
    }
}


