/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig : TLSConfig refers to TLS configuration for a client.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig {
    #[serde(rename = "caCertSecret", skip_serializing_if = "Option::is_none")]
    pub ca_cert_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "clientCertSecret", skip_serializing_if = "Option::is_none")]
    pub client_cert_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "clientKeySecret", skip_serializing_if = "Option::is_none")]
    pub client_key_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "insecureSkipVerify", skip_serializing_if = "Option::is_none")]
    pub insecure_skip_verify: Option<bool>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig {
    /// TLSConfig refers to TLS configuration for a client.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodTlsConfig {
            ca_cert_secret: None,
            client_cert_secret: None,
            client_key_secret: None,
            insecure_skip_verify: None,
        }
    }
}


