/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitArtifact {
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Directory to clone the repository. We clone complete directory because GitArtifact is not limited to any specific Git service providers. Hence we don't use any specific git provider client.
    #[serde(rename = "cloneDirectory", skip_serializing_if = "Option::is_none")]
    pub clone_directory: Option<String>,
    #[serde(rename = "creds", skip_serializing_if = "Option::is_none")]
    pub creds: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitCreds>>,
    #[serde(rename = "filePath", skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
    #[serde(rename = "insecureIgnoreHostKey", skip_serializing_if = "Option::is_none")]
    pub insecure_ignore_host_key: Option<bool>,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "remote", skip_serializing_if = "Option::is_none")]
    pub remote: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitRemoteConfig>>,
    #[serde(rename = "sshKeySecret", skip_serializing_if = "Option::is_none")]
    pub ssh_key_secret: Option<Box<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitArtifact {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitArtifact {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodGitArtifact {
            branch: None,
            clone_directory: None,
            creds: None,
            file_path: None,
            insecure_ignore_host_key: None,
            r#ref: None,
            remote: None,
            ssh_key_secret: None,
            tag: None,
            url: None,
        }
    }
}


