/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLabelValueFrom {
    #[serde(rename = "expression")]
    pub expression: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLabelValueFrom {
    pub fn new(expression: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLabelValueFrom {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLabelValueFrom {
            expression,
        }
    }
}


