/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmqpExchangeDeclareConfig {
    #[serde(rename = "autoDelete", skip_serializing_if = "Option::is_none")]
    pub auto_delete: Option<bool>,
    #[serde(rename = "durable", skip_serializing_if = "Option::is_none")]
    pub durable: Option<bool>,
    #[serde(rename = "internal", skip_serializing_if = "Option::is_none")]
    pub internal: Option<bool>,
    #[serde(rename = "noWait", skip_serializing_if = "Option::is_none")]
    pub no_wait: Option<bool>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmqpExchangeDeclareConfig {
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmqpExchangeDeclareConfig {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmqpExchangeDeclareConfig {
            auto_delete: None,
            durable: None,
            internal: None,
            no_wait: None,
        }
    }
}


