/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSelector : Selector represents conditional operation to select K8s objects.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSelector {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSelector {
    /// Selector represents conditional operation to select K8s objects.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSelector {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSelector {
            key: None,
            operation: None,
            value: None,
        }
    }
}


