/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmount : Amount represent a numeric amount.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmount {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmount {
    /// Amount represent a numeric amount.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmount {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodAmount {
            value: None,
        }
    }
}


