/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
    #[serde(rename = "artifact")]
    pub artifact: Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifact>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
    pub fn new(artifact: crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifact) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
            artifact: Box::new(artifact),
        }
    }
}


