/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatus : Status is a common structure which can be used for Status field.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatus {
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodCondition>>,
}

impl IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatus {
    /// Status is a common structure which can be used for Status field.
    pub fn new() -> IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatus {
        IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodStatus {
            conditions: None,
        }
    }
}


