/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLintCronWorkflowRequest {
    #[serde(rename = "cronWorkflow", skip_serializing_if = "Option::is_none")]
    pub cron_workflow: Option<Box<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCronWorkflow>>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLintCronWorkflowRequest {
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLintCronWorkflowRequest {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLintCronWorkflowRequest {
            cron_workflow: None,
            namespace: None,
        }
    }
}


