/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCronWorkflowStatus : CronWorkflowStatus is the status of a CronWorkflow



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCronWorkflowStatus {
    /// Active is a list of active workflows stemming from this CronWorkflow
    #[serde(rename = "active")]
    pub active: Vec<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodObjectReference>,
    /// Conditions is a list of conditions the CronWorkflow may have
    #[serde(rename = "conditions")]
    pub conditions: Vec<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCondition>,
    /// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    #[serde(rename = "lastScheduledTime")]
    pub last_scheduled_time: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCronWorkflowStatus {
    /// CronWorkflowStatus is the status of a CronWorkflow
    pub fn new(active: Vec<crate::models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodObjectReference>, conditions: Vec<crate::models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCondition>, last_scheduled_time: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCronWorkflowStatus {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCronWorkflowStatus {
            active,
            conditions,
            last_scheduled_time,
        }
    }
}


