/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SensorPeriodCreateSensorRequest {
    #[serde(rename = "createOptions", skip_serializing_if = "Option::is_none")]
    pub create_options: Option<Box<crate::models::IoPeriodK8sPeriodApimachineryPeriodPkgPeriodApisPeriodMetaPeriodV1PeriodCreateOptions>>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "sensor", skip_serializing_if = "Option::is_none")]
    pub sensor: Option<Box<crate::models::IoPeriodArgoprojPeriodEventsPeriodV1alpha1PeriodSensor>>,
}

impl SensorPeriodCreateSensorRequest {
    pub fn new() -> SensorPeriodCreateSensorRequest {
        SensorPeriodCreateSensorRequest {
            create_options: None,
            namespace: None,
            sensor: None,
        }
    }
}


